# qboconst.py
# Python file containing constant variables for formatted sections of the QBO file.

from datetime import date, time

DATE_TODAY = "" + date.today().strftime('%Y%m%d%H%M%S') + ".000[-5]"

HEADER = """OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE

<OFX>
<SIGNONMSGSRSV1>
<SONRS>
<STATUS>
<CODE>0
<SEVERITY>INFO
<MESSAGE>OK
</STATUS>
<DTSERVER>""" + DATE_TODAY + """.000[-5]
<LANGUAGE>ENG
<INTU.BID>3000
</SONRS>
</SIGNONMSGSRSV1>
<BANKMSGSRSV1>
<STMTTRNRS>
<TRNUID>""" + DATE_TODAY + """
<STATUS>
<CODE>0
<SEVERITY>INFO
<MESSAGE>OK
</STATUS>
<STMTRS>
<CURDEF>USD
<BANKACCTFROM>
<BANKID>999999999
<ACCTID>999999999999
<ACCTTYPE>CHECKING
</BANKACCTFROM>"""

FOOTER = """<LEDGERBAL>
<BALAMT>0.00
<DTASOF>""" + DATE_TODAY + '.000[-5]' + """
</LEDGERBAL>
<AVAILBAL>
<BALAMT>0.00
<DTASOF>""" +  DATE_TODAY + '.000[-5]' + """
</AVAILBAL>
</STMTRS>
</STMTTRNRS>
</BANKMSGSRSV1>
</OFX>
"""

DATE_START = '<DTSTART>' +  DATE_TODAY + '.000[-5]'

DATE_END = '<DTEND>' +  DATE_TODAY + '.000[-5]'

BANKTRANLIST_START = """
<BANKTRANLIST>
"""

BANKTRANLIST_END = """
</BANKTRANLIST>
"""

TRANSACTION_START = '<STMTTRN>'
TRANSACTION_END = '</STMTTRN>'


